name: Maven Publish

on:
  workflow_dispatch:
    inputs:
      libraryVersion:
        description: 'Library Version'
        required: true
        default: ''
      packageVersion:
        description: 'Package Version'
        required: true
        default: ''

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Assemble Resources
      run: ./download-libs.sh   
      env:
        VERSION: "v${{ github.event.inputs.libraryVersion }}"
      
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
         distribution: 'adopt'
         java-version: '11'

    - name: Publish Maven package
      uses: samuelmeuli/action-maven-publish@v1
      with:
        maven_args: "-e -X -Drevision=${{ github.event.inputs.packageVersion }}"
        server_id: ossrh
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
        nexus_username: ${{ secrets.OSSRH_USERNAME }}
        nexus_password: ${{ secrets.OSSRH_PASSWORD }} 